models.py
from datetime import datetime
from click import password_option
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    email = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(150), nullable=False)
    user_houses = db.relationship('House', backref='user', lazy=True)

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password

    def __repr__(self):
        return '<User %r>' % self.username


class House(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    location = db.Column(db.String(50), nullable=False)
    price = db.Column(db.String(150), nullable=False)
    description = db.Column(db.String(150), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    is_available = db.Column(db.Boolean, default=True)
    photo_filename = db.Column(db.String(255), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, location, price, description, photo_filename, user_id, is_available=True, created_at=datetime.utcnow()):
        self.location = location
        self.price = price
        self.description = description
        self.photo_filename = ''
        self.user_id = user_id
        self.is_available = is_available
        self.created_at = created_at

    def __repr__(self):
        return '<House %r>' % self.location

forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, TextAreaField, BooleanField, FileField, PasswordField
from wtforms.validators import DataRequired

class HouseForm(FlaskForm):
    location = StringField('Location', validators=[DataRequired()])
    price = IntegerField('Price', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    is_available = BooleanField('Available')
    photo = FileField('Photo')

class LoginForm(FlaskForm):
    email = StringField('email', validators=[DataRequired()])
    password = StringField('password', validators=[DataRequired()])

app.py
from flask import Flask, send_from_directory
from models import db
from routes import user_bp, house_bp
from flask_migrate import Migrate
import secrets
from flask_session import Session
from flask_wtf.csrf import CSRFProtect
import os


app = Flask(__name__, static_folder='static')
csrf = CSRFProtect(app)
app.config['SQLALCHEMY_DATABASE_URI'] = r'sqlite:///C:/Users/Adimn/Desktop/frank alx/frank.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
secret_key = secrets.token_hex(16)
app.config['SECRET_KEY'] = secret_key
app.config['SESSION_TYPE'] = 'filesystem'
app.config['SESSION_PERMANENT'] = False
app.config['SESSION_USE_SIGNER'] = True
app.config['UPLOAD_FOLDER'] = 'C:\\Users\\Adimn\\Desktop\\frank alx\\static\\uploads'



@app.route('/static/C:\\Users\\Adimn\\Desktop\\frank alx\\static')
def serve_static(static):
    root_dir = os.path.dirname(os.path.abspath(__file__))
    return send_from_directory(os.path.join(root_dir, 'static'), static)


Session(app)
db.init_app(app)
migrate = Migrate(app, db)

app.register_blueprint(user_bp)
app.register_blueprint(house_bp)

with app.app_context():
    from routes import *

if __name__ == '__main__':
    app.run(debug=True)

routes.py
from flask import Blueprint, render_template, request, session, redirect, url_for, jsonify, flash, send_from_directory
from models import db, User, House
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from werkzeug.utils import secure_filename
from forms import HouseForm, LoginForm
from sqlalchemy.exc import IntegrityError

user_bp = Blueprint('user', __name__)
house_bp = Blueprint('house', __name__)

@user_bp.route('/')
def home():
    return render_template('landingpage.html')
@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = LoginForm()
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password_option = request.form['password']
        password = generate_password_hash(password_option)
        new_user = User(username, email, password)
        db.session.add(new_user)
        try:
            db.session.commit()
            flash('Registration successful')
            return redirect(url_for('user.login'))
        except IntegrityError:
            db.session.rollback()
            flash('Registration failed')
            return redirect(url_for('user.register'))
    return render_template('Registration.html' , form=form)

@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    if 'user_id' in session:
        return redirect(url_for('user.dashboard'))
    user = None
    form = HouseForm()
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            session['user_id'] = user.id
            flash('Login successful', 'success')
            return redirect(url_for('user.dashboard'))  # Redirect to the dashboard route
        else:
            flash('Invalid email or password', 'error')
            return redirect(url_for('user.login'))  # Redirect back to the login page if login fails
    return render_template('login.html', user=user , form=form)

@user_bp.route('/dashboard' )
def dashboard():
    if 'user_id' not in session:
        return redirect(url_for('user.login'))
    user_id = session['user_id']
    user = User.query.filter_by(id=session['user_id']).first()
    houses = House.query.filter_by(user_id=session['user_id']).all()
    form = HouseForm()
    return render_template('dashboard.html', user=user, houses=houses, form=form)

@user_bp.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('user.login'))

@house_bp.route('/houses', methods=['GET'])
def index():
    houses = House.query.all()
    form = HouseForm()
    return render_template('home.html', houses=houses, form=form)

@house_bp.route('/houses', methods=['POST'])
def add_house():
    if 'user_id' not in session:
        return redirect(url_for('user.login'))

    form = HouseForm(request.form)
    if form.validate():
        location = form.location.data
        price = form.price.data
        description = form.description.data
        is_available = form.is_available.data
        created_at = datetime.now()
        user_id = session['user_id']

        # Handle file upload
        photo = form.photo.data
        filename = None
        if photo:
            filename = secure_filename(photo.filename)
            if filename != '':
                photo.save('static/uploads/' + filename)
        else:
            filename = None

        new_house = House(location=location, price=price, description=description,
                          is_available=is_available, created_at=created_at,
                          user_id=user_id, photo_filename=filename)

        db.session.add(new_house)
        db.session.commit()

        flash('New house added!', 'success')
        return redirect(url_for('house.index'))
    
    flash('Invalid form data', 'error')
    return redirect(url_for('house.index'))

@house_bp.route('/upload/<filename>')
def upload(filename):
    return send_from_directory('static/uploads',filename)

@house_bp.route('/houses/<int:house_id>', methods=['GET'])
def get_house(house_id):
    house = House.query.get(house_id)
    if not house:
        return jsonify({'message': 'House not found'})
    
    house_data = {
        'id': house.id,
        'location': house.location,
        'price': house.price,
        'description': house.description,
        'is_available': house.is_available,
        'created_at': house.created_at.strftime('%Y-%m-%d %H:%M:%S'),
        'photo_filename': house.photo_filename
    }
    
    return jsonify({'house': house_data})

templates/Registration.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Registration</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='Registration.css') }}">
  <link rel="stylesheet" type="text/css" href="Registration.css">
</head>
<body>
  <div class="container">
    <h2>Registration</h2>
    <form action="{{ url_for('user.register') }}" method="POST">
      {{ form.csrf_token }} <!-- Include the CSRF token field -->
      <div class="form-group">
        <label for="name">Full Name</label>
        <input type="text" id="name" name="username" placeholder="Enter your full name" required>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" id="email" name="email" placeholder="Enter your email" required>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" id="password" name="password" placeholder="Enter your password" required>
      </div>
      <div class="form-group">
        <label for="confirm-password">Confirm Password</label>
        <input type="password" id="confirm-password" name="confirm_password" placeholder="Confirm your password" required>
      </div>
      <div class="form-group">
        <input type="submit" value="Register">
      </div>
    </form>
    <div class="form-footer">
      <p>Already have an account? <a href="{{ url_for('user.login') }}">Log in</a></p>
    </div>
  </div>
  <div class="footer">
    <p>&copy; 2023 Your Company. All rights reserved.</p>
  </div>
</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css')}}">
  <script src="{{ url_for('static', filename='dashboard.js') }}"></script>
</head>
<body>
  <button id="toggle-button" onclick="toggleProfile()"><i class="fas fa-bars"></i></button>

  <div id="profile-container" style="display: none;">
    <div class="profile-icon">
      <i class="fas fa-user-circle fa-10x"></i>
    </div>
    <div class="profile-text">
      <h1>Welcome, {{ user.username }}!</h1>
      <p>Email: {{ user.email }}</p>
    </div>
    <div class="profile-actions">
      <a href="{{ url_for('user.logout') }}" class="Logout-button">
        <i class="fas fa-sign-out-alt"></i>
        Logout
      </a>
    </div>
    {% for house in houses %}
    <div class="house">
        <img src="{{ url_for('house.upload', filename=house.photo_filename) }}" alt="House Image">
        <h2>{{ house.location }}</h2>
        <p>Price: {{ house.price }}</p>
        <p>Description: {{ house.description }}</p>
    </div>
{% endfor %}
  </div>
<div id="add-house">
  {% include 'home.html' %}
</div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
<head>
  <title>Add New House</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
  <script src="{{ url_for('static', filename='newhouse.js') }}"></script>
</head>
<body>
  <h1>Add New House</h1>
  <button id="add-house-button" class="popup-button" onclick="toggleForm()">+</button>
  <form id="house-form" action="{{ url_for('house.add_house') }}" method="POST" enctype="multipart/form-data" style="display: none;">
    <label for="location">Location:</label>
    <input type="text" id="location" name="location" required>
    <br>
    <label for="price">Price:</label>
    <input type="number" id="price" name="price" required>
    <br>
    <label for="description">Description:</label>
    <textarea id="description" name="description" rows="4" required></textarea>
    <br>
    <label for="is_available">Available:</label>
    <input type="checkbox" id="is_available" name="is_available">
    <br>
    <label for="photo">Photo:</label>
    <input type="file" id="photo" name="photo" accept="image/*" required onchange="previewImage(event)">
    <br>
    <label for="width">Width:</label>
    <input type="number" id="width" name="width" onchange="resizeImage()">
    <br>
    <label for="height">Height:</label>
    <input type="number" id="height" name="height" onchange="resizeImage()">
    <br>
    <div id="preview-container">
      <img id="preview" src="#" alt="Preview">
    </div>
    <br>
    {{ form.csrf_token }}
    <button type="submit">Add House</button>
  </form>
</body>
</html>

templates/landingpage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>SmartHomes</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='landingpage.css') }}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <script src="https://kit.fontawesome.com/59e7057e2f.js" crossorigin="anonymous"></script>
</head>
<body>
  <header>
    <nav>
      <div class="logo">
        <h1>SmartHomes</h1>
      </div>
      <ul class="nav-links">
        <li><a href="#features"><i class="fas fa-home"></i>Home</a></li>
        <li><a href="#features"><i class="fas fa-cogs"></i> Services</a></li>
        <li><a href="#about"><i class="fas fa-info-circle"></i>About</a></li>
        <li><a href="#contact"><i class="fas fa-envelope"></i>Contact</a></li>
      </ul>
      <div class="auth-buttons">
        <a href="{{ url_for('user.login') }}"><i class="fas fa-sign-in-alt"></i>Sign In</a>
        <a href="{{ url_for('user.register') }}"><i class="fas fa-user-plus"></i>Register</a>
     </div>
    </nav>
  </header>

  <section class="hero">
    <div class="hero-content">
      <h2>Welcome to SmartHomes</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed lorem sapien. Nulla facilisi.</p>
      <a class="btn btn-primary" href="/register">Get Started</a>
    </div>
  </section>

  <section id="features" class="features">
    <h2>Types Of Houses</h2>
    <div class="feature-box">
      <div class="feature">
        <img src="{{ url_for('static', filename='image/Hostels.jpg')}}">
        <i class="fa-regular fa-building fa-beat"></i>
        <h3>Apartments</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </div>
      <div class="feature">
        <img src="{{ url_for('static', filename='image/student.jpg')}}">
        <i class="fas fa-bed"></i>
        <h3>BedSitters</h3>
        <p>Sed sed lorem sapien. Nulla facilisi.</p>
      </div>
      <div class="feature">
        <img src="{{ url_for('static', filename='image/rooms.jpg')}}">
        <i class="fas fa-check-circle"></i>
        <h3>Hostels</h3>
        <p>Donec finibus neque ac dui facilisis tempus.</p>
      </div>
    </div>
  </section>

  <section id="about" class="about">
    <h2>About Us</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed lorem sapien. Nulla facilisi.</p>
    <a class="btn btn-secondary" href="#contact">Contact Us</a>
  </section>

  <section id="contact" class="contact">
    <h2>Review Us</h2>
    <form>
      <input type="text" placeholder="Name">
      <input type="email" placeholder="Email">
      <textarea placeholder="Message"></textarea>
      <button type="submit" class="btn btn-primary">Send Message</button>
    </form>
  </section>
  <div>
    {% include 'upload.html' %}
  </div>

  <footer>
    <div class="social-icons">
      <a href="#" class="social-icon"><i class="fab fa-facebook-f"></i> Facebook</a>
      <a href="#" class="social-icon"><i class="fab fa-twitter"></i> Twitter</a>
      <a href="#" class="social-icon"><i class="fab fa-instagram"></i> Instagram</a>
      <a href="#" class="social-icon"><i class="fab fa-linkedin-in"></i> LinkedIn</a>
      <a href="#" class="social-icon"><i class="fab fa-youtube"></i> YouTube</a>
      <a href="#" class="social-icon"><i class="fab fa-google"></i> Gmail</a>
    </div>
    <p>&copy; 2023. All rights reserved.</p>
  </footer>  
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login</title>
</head>
<body>
	<div class="container">
		<h2>Login</h2>
		<form method="POST" action="{{ url_for('user.login') }}">
      {{ form.csrf_token }}
			<div class="form-group">
				<label for="email">Email</label>
				<input type="text" id="email" name="email" placeholder="Enter your email" required>
			</div>
			<div class="form-group">
				<label for="password">Password</label>
				<input type="password" id="password" name="password" placeholder="Enter your password" required>
			</div>
			<div class="form-group">
				<input type="submit" value="Login">
			</div>
		</form>
		<div class="form-footer">
			<p>Don't have an account? <a href="/register">Sign up</a></p>
		</div>
	</div>
	<div class="footer">
		<p>&copy; 2023 Your Company. All rights reserved.</p>
	</div>
</body>
</html>

templates/mvp-project.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='mvp.css') }}">
    <link rel="stylesheet" href="mvp.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>SMART HOMES</title>
</head>
<header>
    
    <div><img id="logo" src="{{ url_for('static', filename='images/home logo.png') }}" alt="loading"></div>
</header>
<body>
  <img src="{{ url_for('static', filename='images/home logo.png') }}" alt="">
  <div class="container">
    <section>
        <form class="search-box">
            <input type="text" placeholder="search...">
            <button>Search</button>
        </form>
        <div>
            <nav>
                <ul class="menu">
                    <li>
                        <a href="#">
                            <i class="fas fa-home"></i>
                            <span class="icon-tex">Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fas fa-info-circle"></i>
                            <span class="icon-tex">About us</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fas fa-cogs"></i>
                            <span class="icon-tex">Services</span>
                        </a>
                        <ul class="sub-menu">
                            <li><a href="#">Single room</a></li>
                            <li><a href="#">Studio Apartment</a></li>
                            <li><a href="#">Bedsitters</a></li>
                            <li><a href="#">1, 2, and Bedroom House</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fas fa-book"></i>
                            <span class="icon-tex">Blog</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fas fa-envelope"></i>
                            <span class="icon-tex">Contact</span>
                        </a>
                    </li>
                    <li>
                      <a href="Registration.html">
                        <i class="fas fa-user-plus"></i>
                          <span class="icon-tex">Register</span>
                      </a>
                  </li>
                </ul>
            </nav>
            <div class="sidebar">
                <div class="main-menu">
                    <button><i class="fas fa-map-marker-alt"></i>Location</button>
                    <ul class="Location">
                        <li><a href="page1.html">Jogoo</a></li>
                        <li><a href="page2.html">Mwembe</a></li>
                        <li><a href="page3.html">Denimark</a></li>
                        <li><a href="page4.html">Nyanchwa</a></li>
                        <li><a href="page5.html">Cathedral</a></li>
                        <li><a href="page6.html">Fort Jesus</a></li>
                        <li><a href="page7.html">Black House</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <main>
        <h1>WELCOME TO SMARTHOMES</h1>
        <div class="images">
            <div class="images-item">
                <img src="Hostels.jpg">
                <div class="image-description">
                    <h3>Hostels</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Nobis fugiat consectetur repellat similique, inventore quae. Facere,
                        fugit incidunt repellendus autem amet blanditiis ducimus voluptate?
                        Animi ipsa quo aspernatur quas maiores!</p>
                    <span class="real-laction">Location Tag</span>
                    <div class="availability">
                        <span class="status-availability">Available</span>
                        <span class="count">5 Rooms Available</span>
                    </div>
                </div>
            </div>
            <div class="images-item">
                <img src="{{ url_for('static', filename='images/rooms.jpg') }}">
                <div class="image-description">
                    <h3>Single Rooms</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Nobis fugiat consectetur repellat similique, inventore quae. Facere,
                        fugit incidunt repellendus autem amet blanditiis ducimus voluptate?
                        Animi ipsa quo aspernatur quas maiores!</p>
                    <span class="real-laction">Location Tag</span>
                    <div class="availability">
                        <span class="status available">Available</span>
                        <span class="count">5 Rooms Available</span>
                    </div>
                </div>
            </div>
            <div class="images-item">
                <img src="{{ url_for('static', filename='images/archdaily.jpg') }}">
                <div class="image-description">
                    <h3>1, 2, 3 Bedroom Houses</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Nobis fugiat consectetur repellat similique, inventore quae. Facere,
                        fugit incidunt repellendus autem amet blanditiis ducimus voluptate?
                        Animi ipsa quo aspernatur quas maiores!</p>
                    <span class="real-laction">Location Tag</span>
                    <div class="availability">
                        <span class="status-availability">Available</span>
                        <span class="count">5 Rooms Available</span>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
<footer class="foot">
    <div class="social-icon">
        <a href="#" class="icon-link"><i class="fab fa-facebook"></i></a>
        <a href="#" class="icon-link"><i class="fab fa-twitter"></i></a>
        <a href="#" class="icon-link"><i class="fab fa-instagram"></i></a>
        <a href="#" class="icon-link"><i class="fab fa-linkedin"></i></a>
    </div>
</footer>
</body>
</html>

templates/upload.html
<!DOCTYPE html>
<html>
<head>
    <title>Landing Page</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='upload.css') }}">
</head>
<body>
    <h1>Welcome to the Landing Page!</h1>

    {% for house in houses %}
        <div class="house">
            <img src="{{ url_for('house.upload', filename=house.photo_filename) }}" alt="House Image">
            <h2>{{ house.location }}</h2>
            <p>Price: {{ house.price }}</p>
            <p>Description: {{ house.description }}</p>
        </div>
    {% endfor %}

    <script src="{{ url_for('static', filename='landingpage.js') }}"></script>
</body>
</html>